# Generated by Django 2.2.28 on 2025-03-11 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20250311_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
